name: YUVA DESING AND CONSTRACTION
favicon: null
layout_spectrum: 0.7681818660348654
typography_spectrum: 0.17975482903420925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07742507406510413
  lightness: 0.9878755011595786
  saturation: 0.3041019707452506
  rhythmicContrast: 0.057887685718014836
purpose: []
